/**
 * CourseLink - Comprehensive Course Data Store
 * Extracted and mapped from Google Sheets
 */

const COURSE_DATA = [
  // ================= HSC 2026 - HIGHER MATH =================
  {
    id: "hsc26-math-c1",
    title: "ACS HSC 26 Higher Math Cycle 1",
    shortTitle: "Math Cycle 1",
    batch: "HSC 26",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 1,
    link: "https://t.me/+2VXPpBsl1MdjMDBl",
    image: "images/acsm271.png",
    status: "available",
    featured: true,
    description: "Higher Mathematics first paper & fundamentals cycle for HSC 2026 batch.",
    tags: ["hsc 26", "2026", "math", "higher math", "acs", "cycle 1", "c1", "matematics", "gonit"]
  },
  {
    id: "hsc26-math-c2",
    title: "ACS HSC 26 Higher Math Cycle 2",
    shortTitle: "Math Cycle 2",
    batch: "HSC 26",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 2,
    link: "https://t.me/+AKlmN65bcCIwYmU9",
    image: "images/acsm272.png",
    status: "available",
    featured: false,
    description: "Higher Mathematics cycle 2 comprehensive lectures and practice sheets.",
    tags: ["hsc 26", "2026", "math", "higher math", "acs", "cycle 2", "c2"]
  },
  {
    id: "hsc26-math-c3",
    title: "ACS HSC 26 Higher Math Cycle 3",
    shortTitle: "Math Cycle 3",
    batch: "HSC 26",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 3,
    link: "https://t.me/+uE6cs8JGS-w2Yzc9",
    image: "images/acsm273.jpg",
    status: "available",
    featured: false,
    description: "Calculus, Differentiation and Algebra mastery cycle for HSC 26.",
    tags: ["hsc 26", "2026", "math", "higher math", "acs", "cycle 3", "c3", "calculus"]
  },
  {
    id: "hsc26-math-c4",
    title: "ACS HSC 26 Higher Math Cycle 4",
    shortTitle: "Math Cycle 4",
    batch: "HSC 26",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 4,
    link: "https://t.me/acsphysicscycle4mdtheboss",
    image: "images/acsm274.png",
    status: "available",
    featured: false,
    description: "Integration and Advanced Coordinate Geometry modules.",
    tags: ["hsc 26", "2026", "math", "higher math", "acs", "cycle 4", "c4"]
  },
  {
    id: "hsc26-math-c5",
    title: "ACS HSC 26 Higher Math Cycle 5",
    shortTitle: "Math Cycle 5",
    batch: "HSC 26",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 5,
    link: "https://t.me/+-LzfFNTc5uwzNzk1",
    image: "images/acsm275.png",
    status: "available",
    featured: false,
    description: "2nd Paper Higher Math advanced problem solving cycle.",
    tags: ["hsc 26", "2026", "math", "higher math", "acs", "cycle 5", "c5"]
  },
  {
    id: "hsc26-math-c6",
    title: "ACS HSC 26 Higher Math Cycle 6",
    shortTitle: "Math Cycle 6",
    batch: "HSC 26",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 6,
    link: "https://t.me/+TELwxJaSjexlYzU1",
    image: "images/acsm276.jpg",
    status: "available",
    featured: false,
    description: "Statics, Dynamics & Complete Revision cycle for HSC 26.",
    tags: ["hsc 26", "2026", "math", "higher math", "acs", "cycle 6", "c6", "final"]
  },

  // ================= HSC 2026 - PHYSICS =================
  {
    id: "hsc26-phys-c1",
    title: "ACS HSC 26 Physics Cycle 1",
    shortTitle: "Physics Cycle 1",
    batch: "HSC 26",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 1,
    link: "https://t.me/+-QWIZo1ntN5kNDk1",
    image: "images/acsp271.jpg",
    status: "available",
    featured: true,
    description: "Vector, Kinematics and Newtonian Mechanics foundation cycle.",
    tags: ["hsc 26", "2026", "physics", "phy", "acs", "cycle 1", "c1", "vector", "mechanics"]
  },
  {
    id: "hsc26-phys-c2",
    title: "ACS HSC 26 Physics Cycle 2",
    shortTitle: "Physics Cycle 2",
    batch: "HSC 26",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 2,
    link: "https://t.me/+DSgAwYTl0VhhNjJl",
    image: "images/acsp272.jpg",
    status: "available",
    featured: false,
    description: "Work, Power, Energy and Gravitation cycle for HSC 26.",
    tags: ["hsc 26", "2026", "physics", "phy", "acs", "cycle 2", "c2", "energy", "gravitation"]
  },
  {
    id: "hsc26-phys-c3",
    title: "ACS HSC 26 Physics Cycle 3",
    shortTitle: "Physics Cycle 3",
    batch: "HSC 26",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 3,
    link: "https://t.me/+bIoHfJ0RfZQ0NWU1",
    image: "images/acsp273.jpg",
    status: "available",
    featured: false,
    description: "Structural Properties of Matter and Periodic Motion cycle.",
    tags: ["hsc 26", "2026", "physics", "phy", "acs", "cycle 3", "c3", "shm", "waves"]
  },
  {
    id: "hsc26-phys-c4",
    title: "ACS HSC 26 Physics Cycle 4",
    shortTitle: "Physics Cycle 4",
    batch: "HSC 26",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 4,
    link: "https://t.me/+-UDY-kiJO1U1NzQ1",
    image: "images/acsp274.jpg",
    status: "available",
    featured: false,
    description: "Thermodynamics and Ideal Gas modules for HSC 26.",
    tags: ["hsc 26", "2026", "physics", "phy", "acs", "cycle 4", "c4", "thermo"]
  },
  {
    id: "hsc26-phys-c5",
    title: "ACS HSC 26 Physics Cycle 5",
    shortTitle: "Physics Cycle 5",
    batch: "HSC 26",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 5,
    link: "https://t.me/+VzxBnjP6kIc0Yzc1",
    image: "images/acsp275.jpg",
    status: "available",
    featured: false,
    description: "Static Electricity & Current Electricity in-depth cycle.",
    tags: ["hsc 26", "2026", "physics", "phy", "acs", "cycle 5", "c5", "current", "circuits"]
  },
  {
    id: "hsc26-phys-c6",
    title: "ACS HSC 26 Physics Cycle 6",
    shortTitle: "Physics Cycle 6",
    batch: "HSC 26",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 6,
    link: "https://t.me/+1HpBZ3r4Do84NjFl",
    image: "images/acsp274.jpg",
    status: "available",
    featured: false,
    description: "Optics, Modern Physics and Electronics complete cycle.",
    tags: ["hsc 26", "2026", "physics", "phy", "acs", "cycle 6", "c6", "optics", "modern physics"]
  },

  // ================= HSC 2026 - CHEMISTRY =================
  {
    id: "hsc26-chem-c1",
    title: "ACS HSC 26 Chemistry Cycle 1",
    shortTitle: "Chemistry Cycle 1",
    batch: "HSC 26",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "ACS",
    instructor: "ACS Chemistry Faculty",
    cycle: 1,
    link: "https://t.me/+aT_4NDxrWNsyZmE1",
    image: "images/acsc271.jpg",
    status: "available",
    featured: true,
    description: "Qualitative Chemistry and Periodic Properties foundation cycle.",
    tags: ["hsc 26", "2026", "chemistry", "chem", "acs", "cycle 1", "c1", "periodic"]
  },
  {
    id: "hsc26-chem-c2",
    title: "ACS HSC 26 Chemistry Cycle 2",
    shortTitle: "Chemistry Cycle 2",
    batch: "HSC 26",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "ACS",
    instructor: "ACS Chemistry Faculty",
    cycle: 2,
    link: "https://t.me/+WMFoMaQCeIw1ZjI1",
    image: "images/acsc272.jpg",
    status: "available",
    featured: false,
    description: "Chemical Changes, Equilibrium and Energetics cycle.",
    tags: ["hsc 26", "2026", "chemistry", "chem", "acs", "cycle 2", "c2", "equilibrium"]
  },
  {
    id: "hsc26-chem-c3",
    title: "ACS HSC 26 Chemistry Cycle 3",
    shortTitle: "Chemistry Cycle 3",
    batch: "HSC 26",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "ACS",
    instructor: "ACS Chemistry Faculty",
    cycle: 3,
    link: "https://t.me/+enNLBAC5UIszYTg9",
    image: "images/acsc273.jpg",
    status: "available",
    featured: false,
    description: "Environmental Chemistry & 2nd Paper starting modules.",
    tags: ["hsc 26", "2026", "chemistry", "chem", "acs", "cycle 3", "c3"]
  },
  {
    id: "hsc26-chem-c4",
    title: "ACS HSC 26 Chemistry Cycle 4",
    shortTitle: "Chemistry Cycle 4",
    batch: "HSC 26",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "ACS",
    instructor: "ACS Chemistry Faculty",
    cycle: 4,
    link: "https://t.me/+0xcq7sgbCBYzZmJl",
    image: "images/acsc274.jpg",
    status: "available",
    featured: false,
    description: "Organic Chemistry foundational reactions and mechanism cycle.",
    tags: ["hsc 26", "2026", "chemistry", "chem", "acs", "cycle 4", "c4", "organic"]
  },
  {
    id: "hsc26-chem-c5",
    title: "ACS HSC 26 Chemistry Cycle 5",
    shortTitle: "Chemistry Cycle 5",
    batch: "HSC 26",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "ACS",
    instructor: "ACS Chemistry Faculty",
    cycle: 5,
    link: "https://t.me/+21g9ahKbXgRhMzg9",
    image: "images/acsc275.jpg",
    status: "available",
    featured: false,
    description: "Quantitative Chemistry and Electrochemistry mastery cycle.",
    tags: ["hsc 26", "2026", "chemistry", "chem", "acs", "cycle 5", "c5", "electro"]
  },
  {
    id: "hsc26-bp-chem-c4",
    title: "HSC 26 BP Chemistry Cycle 4",
    shortTitle: "BP Chem Cycle 4",
    batch: "HSC 26",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "Bondi Pathshala",
    instructor: "Saikat Sir (BP Faculty)",
    cycle: 4,
    link: "https://web.telegram.org/k/#-3488370224",
    image: "images/bp4.jpg",
    status: "available",
    featured: false,
    description: "Bondi Pathshala Organic Chemistry Master Cycle for HSC 26.",
    tags: ["hsc 26", "2026", "chemistry", "chem", "bp", "bondi pathshala", "saikat", "cycle 4", "c4"]
  },

  // ================= HSC 2027 - CHEMISTRY =================
  {
    id: "hsc27-bp-chem-c1",
    title: "BP HSC 27 Chemistry Cycle 1",
    shortTitle: "BP Chem Cycle 1",
    batch: "HSC 27",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "Bondi Pathshala",
    instructor: "Saikat Sir (BP Faculty)",
    cycle: 1,
    link: "https://t.me/BPHSC27md",
    image: "images/bp1.jpg",
    status: "available",
    featured: true,
    description: "HSC 2027 Bondi Pathshala Chemistry Cycle 1 starting lessons.",
    tags: ["hsc 27", "2027", "chemistry", "chem", "bp", "bondi pathshala", "saikat", "cycle 1", "c1"]
  },
  {
    id: "hsc27-bp-chem-c2",
    title: "BP HSC 27 Chemistry Cycle 2",
    shortTitle: "BP Chem Cycle 2",
    batch: "HSC 27",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "Bondi Pathshala",
    instructor: "Saikat Sir (BP Faculty)",
    cycle: 2,
    link: "https://t.me/bp27chemistry",
    image: "images/bp2.jpg",
    status: "available",
    featured: false,
    description: "HSC 2027 Bondi Pathshala Chemistry Cycle 2 deep dive.",
    tags: ["hsc 27", "2027", "chemistry", "chem", "bp", "bondi pathshala", "saikat", "cycle 2", "c2"]
  },
  {
    id: "hsc27-bp-chem-c3",
    title: "BP HSC 27 Chemistry Cycle 3",
    shortTitle: "BP Chem Cycle 3",
    batch: "HSC 27",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "Bondi Pathshala",
    instructor: "Saikat Sir (BP Faculty)",
    cycle: 3,
    link: "https://t.me/bpchemi",
    image: "images/bp3.jpg",
    status: "available",
    featured: false,
    description: "HSC 2027 Bondi Pathshala Chemistry Cycle 3 advanced topics.",
    tags: ["hsc 27", "2027", "chemistry", "chem", "bp", "bondi pathshala", "saikat", "cycle 3", "c3"]
  },
  {
    id: "hsc27-bp-chem-c4",
    title: "HSC 27 BP Chemistry Cycle 4",
    shortTitle: "BP Chem Cycle 4",
    batch: "HSC 27",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "Bondi Pathshala",
    instructor: "Saikat Sir (BP Faculty)",
    cycle: 4,
    link: "",
    image: "images/bp4_27.jpg",
    status: "upcoming",
    featured: false,
    description: "HSC 2027 Bondi Pathshala Chemistry Cycle 4 (Upcoming release).",
    tags: ["hsc 27", "2027", "chemistry", "chem", "bp", "bondi pathshala", "cycle 4", "c4", "upcoming"]
  },

  // ================= HSC 2027 - PHYSICS =================
  {
    id: "hsc27-acs-phys-c1",
    title: "ACS HSC 27 Physics Cycle 1",
    shortTitle: "ACS Physics Cycle 1",
    batch: "HSC 27",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 1,
    link: "https://t.me/ACSphysicsCycel1",
    image: "images/acsp1.jpg",
    status: "available",
    featured: true,
    description: "First step into HSC Physics - Vector & Kinematics for HSC 27.",
    tags: ["hsc 27", "2027", "physics", "phy", "acs", "cycle 1", "c1", "vector"]
  },
  {
    id: "hsc27-acs-phys-c2",
    title: "ACS HSC 27 Physics Cycle 2",
    shortTitle: "ACS Physics Cycle 2",
    batch: "HSC 27",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 2,
    link: "https://t.me/HSC2027_ACS_Physics_Cycle_2",
    image: "images/acsp2.jpg",
    status: "available",
    featured: false,
    description: "Newtonian Mechanics and Work Energy Power for HSC 27.",
    tags: ["hsc 27", "2027", "physics", "phy", "acs", "cycle 2", "c2", "mechanics"]
  },
  {
    id: "hsc27-acs-phys-c3",
    title: "ACS HSC 27 Physics Cycle 3 (Study Point)",
    shortTitle: "ACS Physics Cycle 3",
    batch: "HSC 27",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 3,
    link: "https://t.me/acsphysicscycle03",
    image: "images/acsp3.jpg",
    status: "available",
    featured: false,
    description: "Gravitation and Structural Properties for HSC 27.",
    tags: ["hsc 27", "2027", "physics", "phy", "acs", "study point", "cycle 3", "c3"]
  },
  {
    id: "hsc27-acs-phys-c4",
    title: "ACS HSC 27 Physics Cycle 4",
    shortTitle: "ACS Physics Cycle 4",
    batch: "HSC 27",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 4,
    link: "https://t.me/acsphysicscyclee4",
    image: "images/acsp4.jpg",
    status: "available",
    featured: false,
    description: "Periodic Motion and Waves for HSC 27.",
    tags: ["hsc 27", "2027", "physics", "phy", "acs", "cycle 4", "c4"]
  },
  {
    id: "hsc27-acs-phys-c5",
    title: "ACS HSC 27 Physics Cycle 5",
    shortTitle: "ACS Physics Cycle 5",
    batch: "HSC 27",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 5,
    link: "",
    image: "images/acsp5.jpg",
    status: "upcoming",
    featured: false,
    description: "Ideal Gas and Thermodynamics for HSC 27 (Coming soon).",
    tags: ["hsc 27", "2027", "physics", "phy", "acs", "cycle 5", "c5", "upcoming"]
  },
  {
    id: "hsc27-acs-phys-c6",
    title: "ACS HSC 27 Physics Cycle 6",
    shortTitle: "ACS Physics Cycle 6",
    batch: "HSC 27",
    subject: "Physics",
    category: "Physics",
    provider: "ACS",
    instructor: "ACS Physics Faculty",
    cycle: 6,
    link: "",
    image: "images/acsp6.jpg",
    status: "upcoming",
    featured: false,
    description: "2nd Paper Physics Modules for HSC 27 (Coming soon).",
    tags: ["hsc 27", "2027", "physics", "phy", "acs", "cycle 6", "c6", "upcoming"]
  },

  // ================= HSC 2027 - HIGHER MATH =================
  {
    id: "hsc27-acs-math-c1",
    title: "ACS HSC 27 Higher Math Cycle 1",
    shortTitle: "ACS Math Cycle 1",
    batch: "HSC 27",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 1,
    link: "https://t.me/acs_math_1",
    image: "images/acsm1.jpg",
    status: "available",
    featured: true,
    description: "Matrix, Determinants and Straight Line foundation for HSC 27.",
    tags: ["hsc 27", "2027", "math", "higher math", "acs", "cycle 1", "c1", "matrix"]
  },
  {
    id: "hsc27-acs-math-c2",
    title: "ACS HSC 27 Higher Math Cycle 2",
    shortTitle: "ACS Math Cycle 2",
    batch: "HSC 27",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 2,
    link: "https://t.me/HSC_27_ACS_Math_Cycle_2",
    image: "images/acsm2.jpg",
    status: "available",
    featured: false,
    description: "Circle and Trigonometry core cycle for HSC 27.",
    tags: ["hsc 27", "2027", "math", "higher math", "acs", "cycle 2", "c2", "trigonometry"]
  },
  {
    id: "hsc27-acs-math-c3",
    title: "ACS HSC 27 Higher Math Cycle 3",
    shortTitle: "ACS Math Cycle 3",
    batch: "HSC 27",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 3,
    link: "https://t.me/llahjsjhsi",
    image: "images/acsm3.jpg",
    status: "available",
    featured: false,
    description: "Differentiation and Calculus Fundamentals for HSC 27.",
    tags: ["hsc 27", "2027", "math", "higher math", "acs", "cycle 3", "c3", "calculus"]
  },
  {
    id: "hsc27-acs-math-c4",
    title: "ACS HSC 27 Higher Math Cycle 4",
    shortTitle: "ACS Math Cycle 4",
    batch: "HSC 27",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 4,
    link: "",
    image: "images/acsm4.jpg",
    status: "upcoming",
    featured: false,
    description: "Integration & Advanced Calculus for HSC 27 (Coming soon).",
    tags: ["hsc 27", "2027", "math", "higher math", "acs", "cycle 4", "c4", "upcoming"]
  },
  {
    id: "hsc27-acs-math-c5",
    title: "ACS HSC 27 Higher Math Cycle 5",
    shortTitle: "ACS Math Cycle 5",
    batch: "HSC 27",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 5,
    link: "",
    image: "images/acsm5.jpg",
    status: "upcoming",
    featured: false,
    description: "2nd Paper Higher Math for HSC 27 (Coming soon).",
    tags: ["hsc 27", "2027", "math", "higher math", "acs", "cycle 5", "c5", "upcoming"]
  },
  {
    id: "hsc27-acs-math-c6",
    title: "ACS HSC 27 Higher Math Cycle 6",
    shortTitle: "ACS Math Cycle 6",
    batch: "HSC 27",
    subject: "Higher Math",
    category: "Math",
    provider: "ACS",
    instructor: "ACS Higher Math Faculty",
    cycle: 6,
    link: "",
    image: "images/acsm6.jpg",
    status: "upcoming",
    featured: false,
    description: "Final Complete Review Cycle for HSC 27 (Coming soon).",
    tags: ["hsc 27", "2027", "math", "higher math", "acs", "cycle 6", "c6", "upcoming"]
  },

  // ================= SPECIAL / ENGINEERING =================
  {
    id: "eng-bp-chem-25",
    title: "BP Engineering Chemistry 25",
    shortTitle: "Engineering Chem 25",
    batch: "Engineering",
    subject: "Chemistry",
    category: "Chemistry",
    provider: "Bondi Pathshala",
    instructor: "Saikat Sir (BP)",
    cycle: "Eng 25",
    link: "https://t.me/saikatengichemimdboss",
    image: "images/bpe.jpg",
    status: "available",
    featured: true,
    description: "BUET, CKET & Top Engineering University Admission Preparation by Saikat Sir.",
    tags: ["engineering", "buet", "admission", "chemistry", "chem", "bp", "bondi pathshala", "saikat", "25 batch"]
  }
];

// Subject Filters Metadata
const SUBJECTS = [
  { id: "all", name: "All Subjects", icon: "bi-grid-fill" },
  { id: "Physics", name: "Physics", icon: "bi-lightning-charge-fill" },
  { id: "Chemistry", name: "Chemistry", icon: "bi-flask-fill" },
  { id: "Math", name: "Higher Math", icon: "bi-calculator-fill" }
];

// Batches Metadata
const BATCHES = [
  { id: "all", name: "All Batches" },
  { id: "HSC 26", name: "HSC 2026", count: 18, desc: "18 Cycles (Physics, Chemistry & Math)" },
  { id: "HSC 27", name: "HSC 2027", count: 16, desc: "16 Cycles (BP Chemistry, ACS Physics & Math)" },
  { id: "Engineering", name: "Engineering / Special", count: 1, desc: "Engineering Admission & Special Cycles" }
];

window.COURSE_DATA = COURSE_DATA;
window.SUBJECTS = SUBJECTS;
window.BATCHES = BATCHES;
